spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.234.28:3303/cloud?useUnicode=true&characterEncoding=utf-8
    username: ENC(1nDyE6E86ibkNXWM/+qlvQ==)
    password: ENC(hV5qYcPEa9+RgBHCZ6vxeg==)

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sk.cloudmvc.model

qiniu:
  ak: 6QT3AO91Kt5kvfV8Wx5z7yfFWcWtnaittv4EFiPb
  sk: 9L-5L1hMtUQAswyfMRScwrUkDrQj3zjarzWdbAQ1
  bucketName: cloudservice
  dominName: http://q852bwm3z.bkt.clouddn.com/


